# rules.bzl — custom Bazel rules for this monorepo.
#
# Custom rules give you full control over actions (what commands run),
# inputs (what files they read), and outputs (what files they produce).
# They are defined in Starlark and run at ANALYSIS time.

def _generate_header_impl(ctx):
    """Implementation function for the generate_header rule."""
    out = ctx.actions.declare_file(ctx.attr.out)

    # ctx.actions.write creates a file with static content — no shell command needed.
    # For dynamic content (e.g., running a tool), use ctx.actions.run or ctx.actions.run_shell.
    ctx.actions.write(
        output = out,
        content = """\
// Auto-generated by generate_header rule. DO NOT EDIT.
#pragma once
#define PROJECT_NAME "{name}"
#define PROJECT_VERSION "{version}"
""".format(
            name = ctx.attr.project_name,
            version = ctx.attr.version,
        ),
    )

    # DefaultInfo tells Bazel what files this target produces.
    # Without it, dependents can't reference the outputs.
    return [DefaultInfo(files = depset([out]))]

generate_header = rule(
    implementation = _generate_header_impl,
    attrs = {
        "out": attr.string(mandatory = True, doc = "Output filename (e.g. 'version.h')"),
        "project_name": attr.string(mandatory = True, doc = "Project name embedded in the header"),
        "version": attr.string(default = "0.0.0", doc = "Version string embedded in the header"),
    },
    doc = "Generates a C/C++ header file with project name and version constants.",
)
